apiVersion: v1
kind: Service
metadata:
  labels:
    app: cakeapi
  name: cakeapi
spec:
  ports:
  - name: "8080"
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: cakeapi
  type: ClusterIP